vim.cmd("command! PIN PlugInstall")
vim.keymap.set("n", "<space>cc", vim.lsp.buf.hover, {})
vim.keymap.set({ "n", "v" }, "<space>ca", vim.lsp.buf.code_action, {})
vim.keymap.set({ "n", "v" }, "<space>ren", vim.lsp.buf.rename, {})
vim.keymap.set({ "n", "v" }, "<space>w", ":WhichKey<CR>")
vim.keymap.set({ "n", "v" }, "<space>ff", ":Telescope find_files<CR>", {})
vim.keymap.set({ "n", "v" }, "<space>fg", ":Telescope grep_string<CR>", {})
vim.keymap.set({ "n", "v" }, "<space>fd", ':lua require("conform").format({async = true})<CR>', {})
vim.keymap.set({ "n", "v" }, "<space>c/", ':Commentary<CR>', {})
vim.keymap.set("n", "<C-r>", ":source /home/colada/.config/nvim/init.lua<CR>", {})
vim.keymap.set("n", "L", ":Neotree action=focus toggle=true<CR>", {})
vim.keymap.set("n", "<C-Tab>", "<C-w>w", {})
